version: 2.1
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
    - image: circleci/node:12.14.1
      # - image: mongo:4.2.0 # and this image as the secondary service container
    steps:
    - checkout
    - run:
        name: update-npm
        command: sudo npm install -g npm@latest
    - restore_cache:
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: install-npm-wee
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: Launching unit test
        command: npm run test:unit
    - run:
        name: Launching build
        command: npm run build
    - run:
        name: Launching linter
        command: npm run lint

workflows:
  version: 2
  workflow:
    jobs:
    - build